# prometheus.yml
scrape_configs:
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9100']
  - job_name: 'leanstore'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8080']
