coverage:
  round: down
  range: 30..100
  precision: 2
  status:
    patch:
      default:
        target: 60%
        threshold: 1%
        base: auto
    project:
      default:
        target: 57%
        threshold: 1%
        base: auto

ignore:
  - "tools"
  - "build"
  - "dist"
  - "docker"
  - "docs"
  - "examples"
  - "scripts"
  - "tests"
