name: PR Title

on:
  pull_request:
    branches: [ master ]
      types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Conventional Commits Check
        uses: webiny/action-conventional-commits
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          allowed-commit-types: "feat,fix,perf,chore,revert"
