name: Conventional Commits Check

on:
  pull_request:
    branches: [ master ]
    types: [opened, edited, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Conventional Commits Check
        uses: agenthunt/conventional-commit-checker-action@v2.0.0
