name: PR Title

on:
  pull_request:
    branches: [ master ]
      types: [opened, synchronize, reopened, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Conventional Commits Check
        uses: ytanikin/PRConventionalCommits@1.1.0
        with:
          task_types: '["feat","fix","perf","chore","revert"]'
