name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  check-signed-commits:
    name: Signed Commits
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Signed Commits Validation
        uses: 1Password/check-signed-commits-action@v1